name: Omochi

on:
  push:
    branches:
      - main

env: # 共通環境變數
  RUBY_VERSION: '3.2.2'
  NODE_VERSION: '22'
  RAILS_ENV: production
  RAILS_MASTER_KEY: ${{ secrets.RAILS_SECRET_KEY }}

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # 預先做成腳本的動作，不需要自己下命令
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with: # 預先動作的額外設定，這邊是設定 Ruby 版本
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - run: gem install specific_install
    - run: gem specific_install -l https://github.com/mikik0/omochi.git
    - run: omochi verify --github
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: yarn install # 直接執行命令的情況
    - run: echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV
    - run: bundle exec rake assets:precompile
    - name: Archive precompiled assets
      uses: actions/upload-artifact@v3
      with:
        name: assets
        path: public/
        retention-days: 7