name: Omochi

on:
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  RUBY_VERSION: '3.2.2'
  NODE_VERSION: '22'
  RAILS_ENV: production

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub CLI
      uses: sersoft-gmbh/setup-gh-cli-action@v2

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - run: gem install specific_install
    - run: gem specific_install -l https://github.com/mikik0/omochi.git
    - run: omochi verify --github
